### ISSUE TITLE
Error: Maximum call stack exceeded

### ISSUE THREAD

**Issue by frux** [staylor/react-helmet-async#11] opened 2018-05-23 12:18 UTC
I ran into a problem with `react@16` and `react-helmet-async`. In version 16 every children contains cyclic property `._owner.alternate.alternate.alternate.alternate...`. You compare props with `deep-equal` so it causes an error "Maximum call stack exceeded".

![image](https://user-images.githubusercontent.com/4231003/40423468-1f974faa-5eac-11e8-8fd4-80e0ebb8544c.png)

**Comment by staylor** [comment] 2018-07-03 18:56
can you give me some example code you used to see this issue? would be happy to address if I can reproduce clearly

**Comment by theKashey** [comment] 2018-08-15 11:52
https://github.com/staylor/react-helmet-async/blob/9ccb8c0425ecc253272e420cf2d92d2b9beb2cbf/src/index.js#L58

calling deepEqual on this.props, having ReactElements inside props.children - that is endless recursion.

Use https://github.com/FormidableLabs/react-fast-compare instead of deepEqual, and that's done.

**Comment by Oblosys** [comment] 2018-08-31 08:28
Looks like this is the same issue as nfl/react-helmet#373.

**Comment by staylor** [comment] 2018-08-31 21:31
marking closed since #22 has been merged

**Closed by staylor** 2018-08-31 21:31 UTC

**Comment by Oblosys** [comment] 2018-09-01 13:12
Thanks for the fix!
